# fly.toml app configuration file generated for rails-ss on 2023-11-15T14:26:06-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rails-ss"
swap_size_mb = 512
primary_region = "gru"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[mounts]
source = "db_rails_ss"
destination = "/rails/db/production"
processes = ["app"]
